-- Tripyfull schema baseline.
--
-- Squashed from the original V1–V12 migrations (2026-09) while the only database
-- was a developer's local one. Tables are listed parents first.

-- Users & reference data ---------------------------------------------------------

CREATE TABLE users (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      varchar(255) NOT NULL,
    email         varchar(255),
    password      varchar(255) NOT NULL,
    base_currency varchar(3),
    language      varchar(10),
    region        varchar(255),
    date_format   varchar(20),
    time_format   varchar(10),
    CONSTRAINT users_username_key UNIQUE (username),
    CONSTRAINT users_email_key    UNIQUE (email)
);

CREATE TABLE countries (
    code   varchar(2)   PRIMARY KEY,
    name   varchar(255) NOT NULL,
    region varchar(255)
);

CREATE TABLE cities (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar(255) NOT NULL,
    country_code varchar(2)   NOT NULL REFERENCES countries (code),
    latitude     double precision,
    longitude    double precision,
    population   bigint  NOT NULL DEFAULT 0,
    popular      boolean NOT NULL
);

-- Trips ----------------------------------------------------------------------------

CREATE TABLE trips (
    id            uuid PRIMARY KEY,
    owner_id      bigint       NOT NULL REFERENCES users (id),
    title         varchar(255) NOT NULL,
    destination   varchar(255),
    start_date    date,
    end_date      date,
    status        varchar(255) NOT NULL,
    base_currency varchar(3),
    cover_image   varchar(500),
    CONSTRAINT trips_status_check CHECK (status IN ('DRAFT', 'PLANNED', 'ACTIVE', 'COMPLETED'))
);

-- Place library --------------------------------------------------------------------

CREATE TABLE places (
    id                uuid PRIMARY KEY,
    owner_id          bigint       NOT NULL REFERENCES users (id),
    name              varchar(255) NOT NULL,
    type              varchar(32),
    description       varchar(2000),
    address           varchar(255),
    city              varchar(255),
    country           varchar(2),
    latitude          numeric(10, 7),
    longitude         numeric(10, 7),
    osm_id            varchar(255),
    source            varchar(16) NOT NULL,
    visibility        varchar(16) NOT NULL,
    audience          varchar(8)  NOT NULL DEFAULT 'ALL',
    rating            integer     NOT NULL DEFAULT 3,
    rating_comment    varchar(500),
    visit_minutes     integer,
    needs_booking     boolean     NOT NULL DEFAULT false,
    needs_preparation boolean     NOT NULL DEFAULT false,
    created_at        timestamp(6) with time zone,
    CONSTRAINT places_type_check CHECK (type IN ('SIGHTSEEING', 'BEACH', 'NATURE', 'RESTAURANT', 'MUSEUM', 'VIEWPOINT',
                                                 'PORT', 'AIRPORT', 'NEIGHBORHOOD', 'PARK', 'SHOP', 'OTHER')),
    CONSTRAINT places_visibility_check CHECK (visibility IN ('PUBLIC', 'PRIVATE'))
);

CREATE TABLE place_photos (
    place_id uuid NOT NULL REFERENCES places (id),
    url      varchar(1000)
);

CREATE TABLE place_links (
    place_id uuid NOT NULL REFERENCES places (id),
    url      varchar(1000)
);

CREATE TABLE place_folders (
    id         uuid PRIMARY KEY,
    owner_id   bigint       NOT NULL REFERENCES users (id),
    trip_id    uuid         REFERENCES trips (id),
    name       varchar(255) NOT NULL,
    color      varchar(255),
    created_at timestamp(6) with time zone NOT NULL
);

CREATE TABLE folder_places (
    folder_id uuid NOT NULL REFERENCES place_folders (id),
    place_id  uuid NOT NULL REFERENCES places (id),
    PRIMARY KEY (folder_id, place_id)
);

-- Places shortlisted for a trip.
CREATE TABLE trip_places (
    trip_id  uuid NOT NULL REFERENCES trips (id),
    place_id uuid NOT NULL REFERENCES places (id),
    PRIMARY KEY (trip_id, place_id)
);
CREATE INDEX idx_trip_places_place ON trip_places (place_id);

-- Bookings -------------------------------------------------------------------------

CREATE TABLE bookings (
    id                  uuid PRIMARY KEY,
    trip_id             uuid         NOT NULL REFERENCES trips (id),
    category            varchar(255),
    name                varchar(255) NOT NULL,
    vendor              varchar(255),
    confirmation_number varchar(255),
    booking_url         varchar(500),
    notes               varchar(2000),
    linked_day_id       uuid,
    -- price
    full_price          numeric(10, 2),
    price_currency      varchar(3),
    exchange_rate       numeric(12, 6),
    paid_simple         boolean NOT NULL,
    -- transport
    transport_mode      varchar(255),
    from_place          varchar(255),
    from_iata           varchar(8),
    from_latitude       double precision,
    from_longitude      double precision,
    to_place            varchar(255),
    to_iata             varchar(8),
    to_latitude         double precision,
    to_longitude        double precision,
    departure_at        timestamp(6),
    arrival_at          timestamp(6),
    departure_terminal  varchar(255),
    arrival_terminal    varchar(255),
    flight_number       varchar(255),
    vessel_name         varchar(255),
    seat                varchar(255),
    cabin               varchar(255),
    car_class           varchar(255),
    -- accommodation / activity
    accommodation_city  varchar(255),
    address             varchar(500),
    latitude            double precision,
    longitude           double precision,
    check_in            date,
    check_in_time       time(0),
    check_out           date,
    check_out_time      time(0),
    room_type           varchar(255),
    guests              integer,
    CONSTRAINT bookings_category_check CHECK (category IN ('TRANSPORTATION', 'ACCOMMODATION', 'ACTIVITY')),
    CONSTRAINT bookings_transport_mode_check CHECK (transport_mode IS NULL OR transport_mode IN
        ('FLIGHT', 'TRAIN', 'FERRY', 'BUS', 'METRO', 'CAR_RENTAL', 'TAXI', 'WALK'))
);

CREATE TABLE payments (
    id         uuid PRIMARY KEY,
    booking_id uuid           NOT NULL REFERENCES bookings (id),
    sequence   integer        NOT NULL,
    amount     numeric(10, 2) NOT NULL,
    due_date   date,
    paid       boolean        NOT NULL,
    paid_date  date
);

CREATE TABLE attachments (
    id           uuid PRIMARY KEY,
    booking_id   uuid         NOT NULL REFERENCES bookings (id),
    file_name    varchar(255) NOT NULL,
    content_type varchar(255),
    size         bigint       NOT NULL,
    storage_key  varchar(255) NOT NULL,
    uploaded_at  timestamp(6) with time zone NOT NULL
);

-- Itinerary ------------------------------------------------------------------------

CREATE TABLE days (
    id                uuid PRIMARY KEY,
    trip_id           uuid    NOT NULL REFERENCES trips (id),
    date              date,                       -- NULL for a buffer day not yet placed
    is_buffer         boolean NOT NULL DEFAULT false,
    city              varchar(255),
    overnight_stay    varchar(255),
    notes             varchar(1000),
    linked_booking_id uuid
);

CREATE TABLE activities (
    id                  uuid PRIMARY KEY,
    day_id              uuid         NOT NULL REFERENCES days (id),
    place_id            uuid         REFERENCES places (id),
    source_booking_id   uuid,                    -- set when the stop was written from a booking
    order_index         integer      NOT NULL,
    type                varchar(255),
    name                varchar(255) NOT NULL,
    address             varchar(255),
    latitude            double precision,
    longitude           double precision,
    start_time          time(0),
    end_time            time(0),
    notes               varchar(2000),
    cost_estimate       numeric(10, 2),
    cost_currency       varchar(3),
    needs_booking       boolean      NOT NULL DEFAULT false,
    travel_mode_to_next varchar(8),
    CONSTRAINT activities_type_check CHECK (type IS NULL OR type IN
        ('SIGHTSEEING', 'BEACH', 'NATURE', 'NEIGHBORHOOD', 'RESTAURANT', 'MEAL_STOP',
         'SHOPPING', 'TRANSPORT', 'ACCOMMODATION', 'OTHER'))
);
CREATE INDEX idx_activities_source_booking ON activities (source_booking_id);

CREATE TABLE expenses (
    id          uuid PRIMARY KEY,
    day_id      uuid           NOT NULL REFERENCES days (id),
    amount      numeric(10, 2) NOT NULL,
    currency    varchar(3),
    category    varchar(255),
    description varchar(255),
    spent_at    timestamp(6),
    CONSTRAINT expenses_category_check CHECK (category IN ('FOOD', 'TRANSPORT', 'ACTIVITY', 'ACCOMMODATION', 'OTHER'))
);

-- To-do list -----------------------------------------------------------------------

CREATE TABLE todos (
    id           uuid PRIMARY KEY,
    trip_id      uuid         NOT NULL REFERENCES trips (id) ON DELETE CASCADE,
    title        varchar(300) NOT NULL,
    notes        varchar(2000),
    group_name   varchar(80),
    due_date     date,
    done         boolean      NOT NULL DEFAULT false,
    order_index  integer      NOT NULL DEFAULT 0,
    template_key varchar(80),                    -- which suggestion it was added from
    created_at   timestamp    NOT NULL DEFAULT now()
);
CREATE INDEX idx_todos_trip ON todos (trip_id);
