
-- Baseline schema, captured from the live dev database on 2026-08-10 (pg_dump 16, schema-only).
-- Existing databases are baselined past this migration (spring.flyway.baseline-on-migrate=true);
-- fresh databases get the full schema from here. Geo reference data (countries/cities) is
-- seeded by GeoDataSeeder on startup, not by migrations.

CREATE TABLE public.activities (
    id uuid NOT NULL,
    address character varying(255),
    cost_currency character varying(3),
    cost_estimate numeric(10,2),
    end_time time(0) without time zone,
    name character varying(255) NOT NULL,
    notes character varying(2000),
    order_index integer NOT NULL,
    start_time time(0) without time zone,
    type character varying(255),
    day_id uuid NOT NULL,
    place_id uuid,
    travel_mode_to_next character varying(8),
    CONSTRAINT activities_type_check CHECK (((type)::text = ANY ((ARRAY['SIGHTSEEING'::character varying, 'BEACH'::character varying, 'NATURE'::character varying, 'NEIGHBORHOOD'::character varying, 'RESTAURANT'::character varying, 'MEAL_STOP'::character varying, 'SHOPPING'::character varying, 'TRANSPORT'::character varying, 'OTHER'::character varying])::text[])))
);

CREATE TABLE public.attachments (
    id uuid NOT NULL,
    content_type character varying(255),
    file_name character varying(255) NOT NULL,
    size bigint NOT NULL,
    storage_key character varying(255) NOT NULL,
    uploaded_at timestamp(6) with time zone NOT NULL,
    booking_id uuid NOT NULL
);

CREATE TABLE public.bookings (
    id uuid NOT NULL,
    accommodation_city character varying(255),
    address character varying(500),
    arrival_at timestamp(6) without time zone,
    arrival_terminal character varying(255),
    booking_url character varying(500),
    cabin character varying(255),
    car_class character varying(255),
    category character varying(255),
    check_in date,
    check_in_time time(0) without time zone,
    check_out date,
    check_out_time time(0) without time zone,
    confirmation_number character varying(255),
    departure_at timestamp(6) without time zone,
    departure_terminal character varying(255),
    exchange_rate numeric(12,6),
    flight_number character varying(255),
    from_iata character varying(8),
    from_place character varying(255),
    full_price numeric(10,2),
    guests integer,
    latitude double precision,
    linked_day_id uuid,
    longitude double precision,
    name character varying(255) NOT NULL,
    notes character varying(2000),
    paid_simple boolean NOT NULL,
    price_currency character varying(3),
    room_type character varying(255),
    seat character varying(255),
    to_iata character varying(8),
    to_place character varying(255),
    transport_mode character varying(255),
    vendor character varying(255),
    vessel_name character varying(255),
    trip_id uuid NOT NULL,
    CONSTRAINT bookings_category_check CHECK (((category)::text = ANY ((ARRAY['TRANSPORTATION'::character varying, 'ACCOMMODATION'::character varying, 'ACTIVITY'::character varying])::text[]))),
    CONSTRAINT bookings_transport_mode_check CHECK (((transport_mode)::text = ANY ((ARRAY['FLIGHT'::character varying, 'FERRY'::character varying, 'BUS'::character varying, 'METRO'::character varying, 'CAR_RENTAL'::character varying, 'TAXI'::character varying, 'WALK'::character varying])::text[])))
);

CREATE TABLE public.cities (
    id bigint NOT NULL,
    latitude double precision,
    longitude double precision,
    name character varying(255) NOT NULL,
    popular boolean NOT NULL,
    country_code character varying(2) NOT NULL
);

ALTER TABLE public.cities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.countries (
    code character varying(2) NOT NULL,
    name character varying(255) NOT NULL,
    region character varying(255)
);

CREATE TABLE public.days (
    id uuid NOT NULL,
    city character varying(255),
    date date NOT NULL,
    linked_booking_id uuid,
    notes character varying(1000),
    overnight_stay character varying(255),
    trip_id uuid NOT NULL
);

CREATE TABLE public.expenses (
    id uuid NOT NULL,
    amount numeric(10,2) NOT NULL,
    category character varying(255),
    currency character varying(3),
    description character varying(255),
    spent_at timestamp(6) without time zone,
    day_id uuid NOT NULL,
    CONSTRAINT expenses_category_check CHECK (((category)::text = ANY ((ARRAY['FOOD'::character varying, 'TRANSPORT'::character varying, 'ACTIVITY'::character varying, 'ACCOMMODATION'::character varying, 'OTHER'::character varying])::text[])))
);

CREATE TABLE public.folder_places (
    folder_id uuid NOT NULL,
    place_id uuid NOT NULL
);

CREATE TABLE public.payments (
    id uuid NOT NULL,
    amount numeric(10,2) NOT NULL,
    due_date date,
    paid boolean NOT NULL,
    paid_date date,
    sequence integer NOT NULL,
    booking_id uuid NOT NULL
);

CREATE TABLE public.place_folders (
    id uuid NOT NULL,
    color character varying(255),
    created_at timestamp(6) with time zone NOT NULL,
    name character varying(255) NOT NULL,
    owner_id bigint NOT NULL
);

CREATE TABLE public.place_links (
    place_id uuid NOT NULL,
    url character varying(1000)
);

CREATE TABLE public.place_photos (
    place_id uuid NOT NULL,
    url character varying(1000)
);

CREATE TABLE public.places (
    id uuid NOT NULL,
    address character varying(255),
    city character varying(255),
    country character varying(2),
    created_at timestamp(6) with time zone,
    description character varying(2000),
    latitude numeric(10,7),
    longitude numeric(10,7),
    name character varying(255) NOT NULL,
    osm_id character varying(255),
    source character varying(16) NOT NULL,
    type character varying(32),
    visibility character varying(16) NOT NULL,
    owner_id bigint NOT NULL,
    CONSTRAINT places_type_check CHECK (((type)::text = ANY (ARRAY[('SIGHTSEEING'::character varying)::text, ('BEACH'::character varying)::text, ('NATURE'::character varying)::text, ('RESTAURANT'::character varying)::text, ('MUSEUM'::character varying)::text, ('VIEWPOINT'::character varying)::text, ('PORT'::character varying)::text, ('AIRPORT'::character varying)::text, ('NEIGHBORHOOD'::character varying)::text, ('PARK'::character varying)::text, ('SHOP'::character varying)::text, ('OTHER'::character varying)::text]))),
    CONSTRAINT places_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['PUBLIC'::character varying, 'PRIVATE'::character varying])::text[])))
);

CREATE TABLE public.trips (
    id uuid NOT NULL,
    base_currency character varying(3),
    cover_image character varying(500),
    destination character varying(255),
    end_date date,
    start_date date,
    status character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    owner_id bigint NOT NULL,
    CONSTRAINT trips_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'PLANNED'::character varying, 'ACTIVE'::character varying, 'COMPLETED'::character varying])::text[])))
);

CREATE TABLE public.users (
    id bigint NOT NULL,
    base_currency character varying(3),
    date_format character varying(20),
    email character varying(255),
    language character varying(10),
    password character varying(255) NOT NULL,
    region character varying(255),
    time_format character varying(10),
    username character varying(255) NOT NULL
);

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.activities
    ADD CONSTRAINT activities_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.attachments
    ADD CONSTRAINT attachments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT bookings_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cities
    ADD CONSTRAINT cities_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.countries
    ADD CONSTRAINT countries_pkey PRIMARY KEY (code);

ALTER TABLE ONLY public.days
    ADD CONSTRAINT days_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.expenses
    ADD CONSTRAINT expenses_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.folder_places
    ADD CONSTRAINT folder_places_pkey PRIMARY KEY (folder_id, place_id);

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.place_folders
    ADD CONSTRAINT place_folders_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.places
    ADD CONSTRAINT places_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.trips
    ADD CONSTRAINT trips_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT fk76g5jpvf8bcqejvp5d2vgrnjb FOREIGN KEY (trip_id) REFERENCES public.trips(id);

ALTER TABLE ONLY public.days
    ADD CONSTRAINT fk7dspvcfhrejvpgmi5s6s4s5fj FOREIGN KEY (trip_id) REFERENCES public.trips(id);

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fkc52o2b1jkxttngufqp3t7jr3h FOREIGN KEY (booking_id) REFERENCES public.bookings(id);

ALTER TABLE ONLY public.attachments
    ADD CONSTRAINT fkeoc73ujhc29qxfbmtgu3fij3v FOREIGN KEY (booking_id) REFERENCES public.bookings(id);

ALTER TABLE ONLY public.cities
    ADD CONSTRAINT fkkn4qtp6nk6w1elw18hc9bwfqk FOREIGN KEY (country_code) REFERENCES public.countries(code);

ALTER TABLE ONLY public.expenses
    ADD CONSTRAINT fkltx52uqwe6ijojrrm1788ehdl FOREIGN KEY (day_id) REFERENCES public.days(id);

ALTER TABLE ONLY public.activities
    ADD CONSTRAINT fkmta4l2nip09tcig9uc3frjgfu FOREIGN KEY (place_id) REFERENCES public.places(id);

ALTER TABLE ONLY public.folder_places
    ADD CONSTRAINT fkmv40rxnr8sepjs7q8geng6nbl FOREIGN KEY (place_id) REFERENCES public.places(id);

ALTER TABLE ONLY public.places
    ADD CONSTRAINT fkn1r5hk1qk3t2u9vpg8f9vu2cr FOREIGN KEY (owner_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.trips
    ADD CONSTRAINT fkn4gd5nfcc2tdxba2goua3jk55 FOREIGN KEY (owner_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.place_photos
    ADD CONSTRAINT fkoi8oebf8jjtpywy7jdtugstdl FOREIGN KEY (place_id) REFERENCES public.places(id);

ALTER TABLE ONLY public.place_links
    ADD CONSTRAINT fkosot4l3pblgha9e4vrg5vj0tu FOREIGN KEY (place_id) REFERENCES public.places(id);

ALTER TABLE ONLY public.folder_places
    ADD CONSTRAINT fkryqqu3mfw7ccnqmlwuo1joxuy FOREIGN KEY (folder_id) REFERENCES public.place_folders(id);

ALTER TABLE ONLY public.activities
    ADD CONSTRAINT fksfjlubexde07ksblsk6lcchij FOREIGN KEY (day_id) REFERENCES public.days(id);

ALTER TABLE ONLY public.place_folders
    ADD CONSTRAINT fktk3d988eqq5m6b4ss966h2396 FOREIGN KEY (owner_id) REFERENCES public.users(id);

